// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'blue': string;
  'cyan': string;
  'default': string;
  'error': string;
  'green': string;
  'iconWrapper': string;
  'processing': string;
  'red': string;
  'success': string;
  'tag': string;
  'tagText': string;
  'warning': string;
}
export const cssExports: CssExports;
export default cssExports;
