// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  date: string;
  link: string;
  linkContainer: string;
}
export const cssExports: CssExports;
export default cssExports;
