// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'block': string;
  'btn': string;
  'btnDanger': string;
  'btnDashed': string;
  'btnDefault': string;
  'btnLg': string;
  'btnLink': string;
  'btnPrimary': string;
  'btnSm': string;
  'disabled': string;
  'focus': string;
}
export const cssExports: CssExports;
export default cssExports;
