// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  active: string;
  activeItem: string;
  collapsed: string;
  disabled: string;
  hoverMenu: string;
  hoverMenuWrapper: string;
  icon: string;
  menuItem: string;
  subMenu: string;
  submenuArrow: string;
  submenuItem: string;
  submenuTitle: string;
}
export const cssExports: CssExports;
export default cssExports;
