// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bordered': string;
  'card': string;
  'cardHeader': string;
  'content': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
