// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  buttonBetween: string;
  codeContent: string;
  subtitle: string;
}
export const cssExports: CssExports;
export default cssExports;
