// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'icon': string;
  'itemEnter': string;
  'itemEnterActive': string;
  'itemExit': string;
  'itemExitActive': string;
  'message': string;
  'messageContainer': string;
  'messageContent': string;
}
export const cssExports: CssExports;
export default cssExports;
